### ISSUE TITLE
Encoding in Links

### ISSUE THREAD

**Issue by ifcologne** [zendesklabs/zignatures#1]
I want to use the variable {{ticket.id}} in a signature link.

`<a href="example.org/clickhere/?id={{ticket.id}}">Klick here</a>`

Unfortunately the URL get's encoded first, so the variable is gone and couldn't be parsed by zendesk. Any idea how to solve this problem?

**Comment by Sarapulov** [comment]
Interesting... I'll have a look and get back to you here.

**Comment by Sarapulov** [comment]
I can replicate it indeed.

Quick workaround here is to use liquid to share desired URL.

Liquid documentation: https://github.com/shopify/liquid/wiki/liquid-for-designers

If you put the below liquid inside the app setting you should receive clickable `<a>` tag which points to `http://example.org/clickhere/?id=TICKET_ID`
You can save this ugly code into Dynamic Content record and just add that record into app settings. It should do the trick as well.

Let me know if that helps?

INPUT
```
{% assign ticket_url = 'Klick here</a>' | prepend: '<a href="http://example.org/clickhere/?id=__ID__">' | replace: '__ID__', ticket.id %}{{ticket_url}}
```

OUTPUT
![](https://www.evernote.com/shard/s259/sh/6f614dee-55bd-4e71-ae0c-6b7887189969/a66aefca3f9805da/res/6d4841c6-333b-450d-b903-cd0593ed91bf/skitch.png?resizeSmall&width=832)

**Comment by Sarapulov** [comment]
I am going to mark this issue as closed in the mean time.

**Comment by ifcologne** [comment]
Thank's, that solves my issue.
