### ISSUE TITLE
Impossible to activate more than one signature

### ISSUE THREAD

**Issue by Ludovic30** [zendesklabs/zignatures#10]
Hi
Formerly, it was possible to add as many zignatures modules as needed (one per brand for example).
Since a couple of weeks, it's no longer possible : as soon as you have one zignatures module installed on your Zendesk account, if you try to add a another one, the system just edit the one that's installed on your system. And you cannot clone it.

**Comment by Sarapulov** [comment]
Thanks for the feedback Ludovic,
This behaviour is actually intended and defined by `"singleInstall": true,` property in manifest.json file.
The logic behind was to avoid possible conflicts by several Zignatures app trying to inject a text on submit event.
For multibrand scenario I suggest you use Liquid in Zignatures app settings to render desired signature depending on the brand field or any other ticket attribute. You can use conditional Liquid expressions as link below suggests:

https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#if--else

Also check this thread to get some idea how to approach it.

https://support.zendesk.com/hc/en-us/community/posts/360004364908-Agent-Signature-based-on-ticket-channel

I am going to mark this issue as resolved for now.
