### ISSUE TITLE
Can't overwrite old signature anymore

### ISSUE THREAD

**Issue by Onkovat** [zendesklabs/zignatures#11]
I installed the app some months ago. Then deactivated it. I wasn't aware of it and installed it again, noticed that it already was installed and activated it. The old signature showed up. However, regardless what I change now, only the old signature shows up. It's like my changes vanish and only the old settings can be used.

**Comment by Sarapulov** [comment]
Hm...
how did you install it? from marketplace? from this github repo?

**Comment by Onkovat** [comment]
I always installed directly from marketplace. It looks to me like it might be a "different line in the database" that was created with the new install, however, the app only checks for the old or first line in db.

**Comment by Sarapulov** [comment]
I would suggest "traditional" troubleshooting steps:

- save your settings
- uninstall all instances of the app
- install it again from the marketplace, perhaps give it a new name
- apply your settings

If this doesn't help perhaps worth contacting support@zendesk.com about this issue. The way you describe suggests it has nothing to do with the actual app, but rather with they way Zendesk serves the code.

I'll keep this issue as open for now. Let me know if steps above will help resolving it?

**Comment by Onkovat** [comment]
It looks good now. Everything is sat back. I wasn't aware that deactivating could result in such strange results.
But all good now.
Thanks for getting back.

**Comment by Sarapulov** [comment]
Cool!
I will flag this issue as resolved.
Thanks for choosing Zignatures and you are very welcome to leave a feedback about the app here https://www.zendesk.com/apps/support/zignatures/
