### ISSUE TITLE
Zendesk placeholders not populating

### ISSUE THREAD

**Issue by tmfpunderdog** [zendesklabs/zignatures#12]
Hi Andrey! 

Thank you so much for creating Zignatures - I'm really excited to start using it!! This sounds really basic, but I can't figure out what I'm doing wrong. For some reason, when I try to insert standard zendesk placeholders (for example, {{agent.signature}} ), nothing happens. The placeholder disappears when the ticket is updated, but the desired text isn't inserted. I tested it with {{agent.email}} as well - same thing.  Any advice?

Thank you!
Ariana

**Comment by Sarapulov** [comment]
Hi Ariana,
thanks for the feedback.
Typically `{{agent.signature}}` and `{{agent.email}}` are not intended to be used with Zignatures.
You can use other placeholders instead. Such as `{{ticket.assignee.name}}`.
Feel free to tell me what you are trying to achieve I'll do my best to assist you.

**Comment by tmfpunderdog** [comment]
Oh, thanks for getting back to me so quickly! Typically we use our personal signatures to include our name and title, and then have an instance-wide signature that includes our company contact information and legal disclaimers. But, we just started testing proactive texts, and I was looking for something that would remove the signature when our agents send texts rather than emails, which is how I stumbled on Zigantures. So, the feature that allows turning off signatures on individual tickets is perfect. 

But, in trying to re-create our signatures for emails (meaning: name, title, company contact info + disclaimers) I ran into the issue described above. 

{{ticket.assignee.name}} works as a workaround for name - any suggestions about title? I suppose we could create custom roles in zendesk and use {{user.extended_role}} but that seems like it might open another can of worms around permissioning, etc. Let me know what you think!

**Comment by Sarapulov** [comment]
I see,

The placeholders you can use are basically any placeholder listed in the following article.

https://support.zendesk.com/hc/en-us/articles/203662156

For more complex requirement I suggest to use `Liquid`:

https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#if--else

Also check this thread. You may get some idea how others solve it:

https://support.zendesk.com/hc/en-us/community/posts/360004364908

In your case you may need to re-construct original signature into Zignature friendly one. Which will be the mix of text/html and Zendesk placeholders.

If you are still struggling with all of he above feel free to share example of real signature. I can give you hand when I have time.

**Comment by tmfpunderdog** [comment]
It looks like using the placeholder {{ticket.assignee.signature}} rather than {{agent.signature}} does what I need it to - thank you for your help!

**Comment by Sarapulov** [comment]
Nice!
Closing this one.
