### ISSUE TITLE
Font size reduce

### ISSUE THREAD

**Issue by tkapms** [zendesklabs/zignatures#14]
Hi,

I have the problem that all html tags, like "<small>" for example, to reduce the font size are automatically deleted/filtered by the zignatures app. Somebody have a solution for it?

Thanks in advance!

Greets
Torsten

**Comment by Sarapulov** [comment]
Hi Torsten,
I believe what you are referring to is when signature is injected at ticket submit event it removes all fancy html & styling. Is this the issue?
If so, then this is not related to the App itself. This is how Zendesk Comment editor works. It sanitises all "non-standard" HTML. It can only accept what Zendesk thinks is valid & correct. Hence it is a challenge to go with fancy styling and HTML. I haven't found any solution to that so far.
Lemme know if that makes sense.

**Comment by tkapms** [comment]
Hi,

thanks for the quick reply. Not really, cause I tried the zignatures app until now only in our sandbox not in the live system and when I created our different signatures in the app, everytime the html tags like "<small" are deleted by the app, it's not possible to save the change in the app. We have in every of our zignatures a disclaimer part, which we like to have in a smaller font size. So I hope you understand what I mean, thanks!

**Comment by Sarapulov** [comment]
That is actually what I am trying to say here.
Looks like "small" tag is not supported by Zendesk Comment Text Editor. So when App is trying to inject such tag it gets removed by the editor. I just tested it on my end.

**Comment by tkapms** [comment]
Okay, I understand, but in the description and example of the app you use "font-size:14px" and it works, if I use it, it's also deleted zendesk. It's also on the basis of the Zendesk Comment Text Editor?

**Comment by Sarapulov** [comment]
Zendesk Comment Editor is like black box. App is trying to throw all fancy HTML and styling there and never know whet to expect back. I won't be surprised that at the time when App was built it may have less stricter rules. In any case, this kind of problem is not something App can solve. You need to make sure the signature is inline with HTML supported  by Zendesk.

I am going to close this issue for now.
