### ISSUE TITLE
Zignatures - unavailable to use

### ISSUE THREAD

**Issue by andrewleungfung** [zendesklabs/zignatures#15]
Hi, 

I was using Zignatures in my testing account last 2 weeks which has a very good functions on providing customzied signatures. However, it seems Zignatures is not available to use now. Would it be released again? 

Zignatures is definitely one of the best app in Zendesk and we are thinking if we can find workaround without this now. Hope it can be available again. Thank you for reading this!

**Comment by Sarapulov** [comment]
Thanks for raising that.
Zignatures was the part of so-called Labs Apps. Zendesk made a decision to remove this App from the marketplace.
However, you can download & install it from this GitHub repo. This is the same App. Do you know how to do that?

**Comment by andrewleungfung** [comment]
Thank you for getting back!
Sorry I do not have knowledge on how to do that. Do you mind if you could share some guidance on this?
Greatly appreciated again for this!

**Comment by Sarapulov** [comment]
Sure.

1. Go to the Code tab or this link https://github.com/zendesklabs/zignatures

2. Click on "Clone or Download" button and choose Download ZIP.
![](https://cl.ly/5c1822e7bc9b/Image%202020-03-10%20at%206.19.58%20AM.png)

3. That ZIP file is the App you need to upload to your Zendesk as the private App under Setting wheel > APPS:Manage > Upload private App. It will ask to choose a file. Choose that zip file you downloaded. Then follow the steps and App should be installed.

![](https://cl.ly/9bd1f936ef7f/Image%202020-03-10%20at%206.23.01%20AM.png)

I am going to mark this issue as resolved. If you, however, have any problems feel free to contact me.
