### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by nhauville-virtuo** [zendesklabs/zignatures#16]
I am getting the error Cannot read property 'length' of undefined when trying to submit a ticket as Solved. The ticket is via SMS channel and also has a phone call on the thread. Here is the signature:

{% if ticket.tags contains 'send_text' or ticket.via == 'SMS' %}
{% else %}
{{current_user.name}}
{% endif %}

![Zignatures](https://user-images.githubusercontent.com/67115253/87713260-24bac400-c767-11ea-9ee0-effd35a770ca.png)

**Comment by Sarapulov** [comment]
Thanks for reporting.

I may need to replicate that one to tell what is the issue here. I don't believe I've seen it before.
Curios, are you seeing the same error message when submit a comments on a ticket created on non-sms channel?

**Comment by nhauville-virtuo** [comment]
I ended up closing the ticket and then navigating back to it through the user profile and it worked. May have just been a temporary glitch on the page. This is the only time we have seen this error. Although we just started using Zignature 24 hours ago.

**Comment by Sarapulov** [comment]
Thanks for getting back to me. Great it worked out for you.
It could be that Zendesk Application framework cause a temporary glitch making Zignatures behave oddly. If problem returns or you'll manage to replicate it somehow - please let me know.
In the meantime, I will mark this issue as close.
Also, you are more then welcome to provide a feedback to Zignatures app on Zendesk marketplace.
