### ISSUE TITLE
Signatures dont show up when sendeing message

### ISSUE THREAD

**Issue by hakannanan** [zendesklabs/zignatures#17]
Hi,

Noticed that the signature doesnt show up when submitting a message. Used to work some time ago, but don't know when it stopped. We didn't change anything.

Tried to remove html in tes eignature, but even it I put some plain text nothing shows.

Any suggestions how to resolve?

**Comment by Sarapulov** [comment]
hm....
there were no recent changes in the app at all. So hard to say what may have caused an issue.

Are you able to share screenshots with a bit of replication steps? That may help me troubleshooting the issue.

**Comment by Sarapulov** [comment]
Let me know if this is still a problem?
I prefer not to keep GitHub issues under control and rather close them.

**Comment by Sarapulov** [comment]
I am going to mark this one as resolved.

**Comment by ypuyolt** [comment]
Hi, I'm having the same issue with my team. On one account, it shows the app as Hidden, but everyone else can see it. She has no other different settings on her account and I logged in from my same browser. 

<img width="1369" alt="Screen Shot 2020-11-13 at 3 55 15 PM" src="https://user-images.githubusercontent.com/74436434/99131666-a06b3700-25c8-11eb-8f0b-37a4647ca423.png">

This image is from the account I have an Issue with, and this other image is from my account: 

<img width="1375" alt="Screen Shot 2020-11-13 at 3 56 22 PM" src="https://user-images.githubusercontent.com/74436434/99131767-cbee2180-25c8-11eb-9fea-fb2b2f197c05.png">

**Comment by Sarapulov** [comment]
Strange.
When the App is being it is indeed doing so in "hidden mode". So it is expected for this App to be invisible for a short time. Once App is loaded and all required data is collected it makes itself visible. 
By the look at your screenshots, it seems that App remains visible for some reason. Question - when it is invisible does it still adds a signature?

**Comment by ypuyolt** [comment]
Hello,

No, no signatures are added when we reply. Apparently this has been an issue for a few months and when I reviewed her tickets there were no signatures added. I checked if there was maybe any other apps interfering with the Zignatures app but her account has no additional apps than my other agents. I also don’t have any group/user level restrictions on my settings.

**Comment by Sarapulov** [comment]
I am running out of versions what can possibly cause that.
Would you be available for a quick screen share session on, say, Thursday next week?

**Comment by Sarapulov** [comment]
Hey,
let me know if this is still na issue?
