### ISSUE TITLE
Signatures don't show up when sending message

### ISSUE THREAD

**Issue by vivianeantunes** [zendesklabs/zignatures#18]
Hi,

We use the Zendesk System with the Zignatures application, and I would like support for solving a problem.

After activating the agent workspace parameter in the Zendesk Agent settings, signatures are no longer being recorded, see the example below.

![image](https://user-images.githubusercontent.com/77117202/103919174-82b0de80-50ee-11eb-9f24-ca070448f9de.png)

![image](https://user-images.githubusercontent.com/77117202/103919189-87759280-50ee-11eb-82c5-304a303a7f49.png)

![image](https://user-images.githubusercontent.com/77117202/103919200-8ba1b000-50ee-11eb-8644-69edf056b6fb.png)

If the setting is disabled, then the signature writes to the responses of the tickets.

![image](https://user-images.githubusercontent.com/77117202/103919229-93f9eb00-50ee-11eb-8cb0-a29bed16027e.png)

![image](https://user-images.githubusercontent.com/77117202/103919240-96f4db80-50ee-11eb-8c8f-32eb99bc2b8c.png)

**Comment by Sarapulov** [comment]
Thanks for sharing.
This is actually a known issue caused by Zendesk Agent Workspace.
I raised this with Zendesk a while ago. AFAIK they are working on a resolution, but this is not completed yet.
There is not much that can be done in the meantime to make this app work in the Agent Workspace.
I'll keep this issue open for now and ill mark it as resolved then I hear from Zendesk.

**Comment by Sarapulov** [comment]
Hey,
as per my recent test, the issue for the Zignatures App not working in the new Agent Workspace appears to be resolved. Let me know if that is still the case for you? If so I would recommend logout from Zendesk => clean cache & cookies => login and try again. If the issue persists then it is likely you may need a bit longer for the fix to be rolled out to all Zendesk accounts. Let me know if you have any questions.
