### ISSUE TITLE
Toggle "Sign all my comments" not responsive

### ISSUE THREAD

**Issue by ifcologne** [zendesklabs/zignatures#2]
When I use the toggle `no_tickets` (_Sign all my comments_) as an agent, I can deactivate it once, but I'm not able to activate signing again via the toggle. (Of course, I have activated the option itself in the setting.)

**Comment by Sarapulov** [comment]
thanks for reporting this one. I need some time to research on this front.
So far i understood that:

1. you activated `Agents can decided on all comments signature` in app settings
2. as an Agent (not admin) you click on `Sign all my comments` to deactivate it
3. it worked, however when you click on `Sign all my comments` again in the same ticket/session (i.e. you didn't save the ticket) it doesn't activate back. While you expect this toggle to activate the setting back.

Are those replication steps sound correct to you? @ifcologne

**Comment by ifcologne** [comment]
Yes, absolutely correct.

**Comment by Sarapulov** [comment]
Looks like I was able to replicate it even when login as Admin. Looks like a bug indeed. I'll check the code and let you know when it's updated.

**Comment by Sarapulov** [comment]
The issue should be fixed now. It was related to incorrect use of `this` inside JS arrow function.

Just pushed updated version of the app into this github repo. Will submit the update for marketplace later this month.

Thanks again for reporting this issue!
I'll mark it as resolved for now.

**Comment by ifcologne** [comment]
Thanks a lot.
