### ISSUE TITLE
HTML trouble with Zignatures app in Zendesk

### ISSUE THREAD

**Issue by RCROPluriell** [zendesklabs/zignatures#20]
Hello,

I'm testing the Zignatures for agent signatures in Zendesk.
I've some trouble the HTML Code used and the rendering (mainly with the color)

HTML code used:
<div>
<table style="width: 250; font-family: Arial, sans-serif; font-size: 11px;">
<tbody>
<tr>
<td width="30" height="30"><img style="vertical-align: top; margin-right: 3px;" src="https://theme.zdassets.com/theme_assets/11229426/89198540fc0690d1fe5ea72369eec2678823beef.png" width="30" height="30" /></td>
<td valign="baseline"><span style="color: #333333; font-size: 12px; font-weight: bold; margin-top: 2px;">{{current_user.name}} </span></td>
</tr>
</tbody>
</table>
</div>
<div>
<div id="content" style="width: 250; font-family: Arial, sans-serif; font-size: 11px; font-variant: small-caps; margin-left: 2px; margin-top: 5px;"><span style="font-weight: bold; font-style: italic; color: #333333;">{{current_user.signature}}</span><br /><span style="font-weight: bold; font-size: 11px; color: #009966;">TEL:</span> {{current_user.phone}} <br /><span style="font-size: 11px; color: #009966;">Leuvensesteenweg 561, 1930 Zaventem</span><br /><a href="http://www.facq.be" target="_blank"><span style="color: #000000; font-variant: normal;">www.facq.be</span></a></div>
</div>

Rendering:
![Rrendering](https://user-images.githubusercontent.com/89126879/129856383-e749c74b-b108-4748-93c0-52eab3380933.png)

Expected rendering:
![Expected rendering](https://user-images.githubusercontent.com/89126879/129856388-6e5b413d-2f55-4c78-8c17-40400e2b418e.png)

  

Any idea why?

**Comment by Sarapulov** [comment]
Thanks for using Zignatures.
The Zendesk comment editor sanitizes the HTML heavily. So when Zignatures injects a signature a lot of fancy HTML and CSS get removed by Zendesk comment editor.
Try adding your HTML into the Zendesk dynamic content > get the placeholder > add palceholder into Zignatures App settings. This tends to help in the past.
