### ISSUE TITLE
"Comment.appendHtml" The quota has been exceeded

### ISSUE THREAD

**Issue by LyraIT** [zendesklabs/zignatures#22]
Hello,

We are facing an issue with our Zendesk and the plugin Zignatures.
Sometime, when we try to add a comment to an issue, we have this error appered on the top right :

![firefox_2021-06-24_15-15-11](https://user-images.githubusercontent.com/92383729/136979583-550430df-a1c4-408f-aa18-888b616bac43.png)

We are not abel to add this comment unless with a refresh of the window or to force by clicking a lot of time on the button statut change.
This issue appered only on Firefox users, works fine with other web browser.

We tryed to clear cache / reinstall completely firefox like a new environment, but still have the issue. And don't know why some users have this issue and others don't. 

Windows 10 pro x64
Version 1803 or 20h2
Web browser : Firefox (93.0)
No addon.

Any suggestion how to resolve this ?

**Comment by Sarapulov** [comment]
hm...
Can you share the signature code that you are using in the App?

**Comment by LyraIT** [comment]
We are using liquid code in zignature, like this :


{% case ticket.ticket_field_option_title_360014551279 %}

{% when 'Lyra-Support' %}
{{dc.signature_lyra-support}}

...
We are using 34 others signatures like that.
...

{% endcase %}


and use zendesk dynamic content to call the html balise :
<img width="557" alt="Capture d’écran 2021-10-13 155359" src="https://user-images.githubusercontent.com/92383729/137146773-a42acd69-f660-48e3-835c-b8a64f1c6532.png">
<img width="551" alt="Capture d’écran 2021-10-13 161812" src="https://user-images.githubusercontent.com/92383729/137151453-e477064d-bb59-46ec-bdf3-3744c32b0f2a.png">

**Comment by Sarapulov** [comment]
>We are using 34 others signatures like that.

I wonder whether you've tried reducing the amount of versions to, say, 20 and check if the issue is still there?

**Comment by LyraIT** [comment]
I knew you were going to say that.
Unfortunatly, we can't reduce the amount of signatures...they are all used for different services. And because the issue happend only on certain firefox user, i don't know if that's exactly the problem here. They used the same amount of signatures but not exaclty the same signatures.
That why it's hard to identify and reproduced the problem and so to find what is causing this issue...
The issue appered randomly sometime, not always on the same signature and seems to happen after a while of use on zendesk.


Do you have any other idea to find a solution ?

**Comment by Sarapulov** [comment]
hm...
I wonder if that particular user has a particularly longer signature. So it causes an issue.
Also, did you try wrapping the entire signature login inside the Dynamic Content and add that Dynamic Content to the Zigantures App settings? I have a feeling that it may help here as the Dynamic Content is calculated on the server side.
