### ISSUE TITLE
Zignatures Options on Public Reply tab not displayed 

### ISSUE THREAD

**Issue by ifcologne** [zendesklabs/zignatures#4]
One more thing.

When I open a ticket, the Zignatures app loads, but doesn't offer the activated toggle options. Instead it's an empty container with just the app name and logo. This occurs after the first login in Zendesk.

0. Login to Zendesk
1. Open a ticket from the views tab. --> **No options displayed**.
2. Change the tab to "Internal note". --> The Zignatures app get's initialized and the options are available. 
3. click back to "Public Reply" tab. --> The Zignature app works as expected.
4. Click on another Ticket. --> Still everything is perfect, at least for this session.
5. Logout and Login again, start with step 1: --> Zignature app **is not** initialized correctly.

That's not a side effect of your fix earlier today. That was something I've recognized yesterday and what I can still reproduce with the current version. 

Btw. thanks for the short turnaround cycles, I'm ready to ship the app for production use very soon.

**Comment by Sarapulov** [comment]
interesting...
App works for me in Chrome and Safari. In Firefox, however, i seem was able to replicate the issue.
The app still works as it added signature for me, but all UI elements are not displayed as your replication steps suggest. 
Are you also seeing this in Firefox or?

**Comment by ifcologne** [comment]
Yes, now everything makes sense.

That of course is the reason why I didn't noticed this behavior before. I was forced to use a different browser than chrome to test the app in different Zendesk settings. So I just recently tested in Firefox 54.

**Comment by Sarapulov** [comment]
ok, just pushed quick fix for this one. The issue was with app resizing. FireFox doesn't accept `$(document).height()` so had to replace it with `100%`. As per my tests in FF, Chrome and Safari the issue no longer exist.

Latest version pushed to this repo.

Thanks for pointing this one out.

Will mark this issue as resolved.
