### ISSUE TITLE
IE11 - Zignatures Options on Public Reply tab not displayed

### ISSUE THREAD

**Issue by at0mic83** [zendesklabs/zignatures#7]
Hi Guys,

I'm having similar issues with this app appearing in IE11; When staff use Internet Explorer and they open a ticket, the Zignatures app does not appear to load what so ever. 

Login to Zendesk in IE11
Open a ticket from the views tab. --> No options displayed.
Change the tab to "Internal note". --> No options displayed.
Change back to "Public Reply" tab. --> No options displayed.
Click on another Ticket. --> No options displayed.
Logout and Login again, start with step 1: --> No options displayed.

This only occurs in Internet Explorer (which unfortunately being a corporate network IT gets funny about letting staff have other browsers). All other browsers work perfectly.

![ie](https://user-images.githubusercontent.com/30153624/29815189-576242ce-8ce2-11e7-83f0-79252eea5f99.png)
![other](https://user-images.githubusercontent.com/30153624/29815188-575252c4-8ce2-11e7-8e93-c8b967e4526a.png)

**Comment by Sarapulov** [comment]
thanks for reporting this. I'll have a look and when I can.
-AS

**Comment by Sarapulov** [comment]
Just pushed new version (1.5.0) of the app which should work in IE11.
Will mark this issue as resolved.
