### ISSUE TITLE
Not holding settings

### ISSUE THREAD

**Issue by furnaceX** [zendesklabs/zignatures#9]
I've updated some settings and the signature HTML.  But the app keeps reverting back to the defaults.

**Comment by Sarapulov** [comment]
Thanks for reporting this issue. I never heard about this one before and app is installed on number of accounts. I have a feeling it may be related to recent issue with Zendesk App Framework (see below). However, if you are able to replicate the issue please feel free to share replication steps. In the mean time I am going to mark this one as closed.

![](https://cl.ly/0J0q3G190n0x/Image%202018-06-05%20at%2010.09.01%20PM.png)
